import { useEffect, useMemo, useState } from "react";
import GenericPage from "../components/common/GenericPage";
import SearchToolbar from "../components/common/SearchToolbar";
import LoadingState from "../components/common/LoadingState";
import ErrorState from "../components/common/ErrorState";
import StatusBadge from "../components/common/StatusBadge";
import { endpoints, resource } from "../services/resourceService";
import { money, dateText } from "../utils/format";

export default function Credit(){const [rows,setRows]=useState<any[]>([]);const [q,setQ]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const load=async()=>{try{setLoading(true);setError("");setRows(await resource.list<any>(endpoints.credit));}catch(e:any){setError(e.response?.data?.message||"Unable to load credit sales.");}finally{setLoading(false);}};useEffect(()=>{load();},[]);const filtered=useMemo(()=>rows.filter(r=>`${r.invoiceNumber||r.name||""} ${r.customer?.name||r.customerName||""} ${r.status||""}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);return <GenericPage title="Credit Management" subtitle="Review credit sales, customers and outstanding payment status." action="Refresh" onAction={load} toolbar={<SearchToolbar value={q} onChange={setQ} placeholder="Search invoice or customer..."/>}>{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:<div className="table-shell overflow-x-auto"><table className="table-base min-w-[820px]"><thead><tr><th>Reference</th><th>Customer</th><th>Amount</th><th>Date</th><th>Status</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td className="font-semibold">{r.invoiceNumber||r.name||r.id}</td><td>{r.customer?.name||r.customerName||"—"}</td><td className="font-bold">{money(r.totalAmount??r.amount)}</td><td>{dateText(r.createdAt||r.saleDate||r.invoiceDate)}</td><td><StatusBadge status={r.status}/></td></tr>)}{filtered.length===0&&<tr><td colSpan={5} className="p-8 text-center text-sm text-slate-400">No credit records found.</td></tr>}</tbody></table></div>}</GenericPage>;}
