import { useEffect, useMemo, useState } from "react";
import GenericPage from "../components/common/GenericPage";
import SearchToolbar from "../components/common/SearchToolbar";
import LoadingState from "../components/common/LoadingState";
import ErrorState from "../components/common/ErrorState";
import { endpoints, resource } from "../services/resourceService";
import { dateText, number } from "../utils/format";

export default function StockIn(){const [rows,setRows]=useState<any[]>([]);const [q,setQ]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const load=async()=>{try{setLoading(true);setError("");setRows(await resource.list<any>(endpoints.inventory));}catch(e:any){setError(e.response?.data?.message||"Unable to load inventory movements.");}finally{setLoading(false);}};useEffect(()=>{load();},[]);const filtered=useMemo(()=>rows.filter(r=>`${r.product?.name||r.productName||""} ${r.transactionType||r.type||""}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);return <GenericPage title="Add Stock" subtitle="Review inventory movements and stock-in transactions from the backend." action="Refresh" onAction={load} toolbar={<SearchToolbar value={q} onChange={setQ} placeholder="Search product or transaction type..."/>}>{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:<div className="table-shell overflow-x-auto"><table className="table-base min-w-[760px]"><thead><tr><th>Product</th><th>Transaction</th><th>Quantity</th><th>Before</th><th>After</th><th>Date</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td className="font-semibold">{r.product?.name||r.productName||"—"}</td><td>{r.transactionType||r.type||"—"}</td><td>{number(r.quantity)}</td><td>{number(r.beforeStock)}</td><td className="font-bold">{number(r.afterStock)}</td><td>{dateText(r.createdAt)}</td></tr>)}{filtered.length===0&&<tr><td colSpan={6} className="p-8 text-center text-sm text-slate-400">No inventory movements found.</td></tr>}</tbody></table></div>}</GenericPage>}
